wip

diff --git a/.github/workflows/update_secret.yml b/.github/workflows/update_secret.yml
--- a/.github/workflows/update_secret.yml
+++ b/.github/workflows/update_secret.yml
@@ -15,6 +15,7 @@ jobs:
 
     - name: Set up 1Password CLI
       run: |
+        echo "OP_SIGNIN_TOKEN: $OP_SIGNIN_TOKEN"
         # Install and configure 1Password CLI
         sudo -s <<EOF
         curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
@@ -25,7 +26,7 @@ jobs:
         curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
         apt update && apt install -y 1password-cli
         # Configure 1Password CLI with your account details
-        op signin --raw <<< "$OP_SIGNIN_TOKEN"
+        op signin --raw <<< "$OP_SIGNIN_TOKEN" || { echo "Failed to sign in with 1Password CLI"; exit 1; }
         EOF
 
     - name: Set up GitHub CLI
